FROM getmeili/meilisearch
ARG MEILISEARCH_ENVIRONMENT
ARG MEILISEARCH_MASTER_KEY

ENV MEILISEARCH_ENVIRONMENT=${MEILISEARCH_ENVIRONMENT}
ENV MEILISEARCH_MASTER_KEY=${MEILISEARCH_MASTER_KEY}

EXPOSE 7700
